SCR_MissionHeader {
 World "{76F7DAF55FDB4796}World/29th_Training_Eden.ent"
 m_sName "29th_Training_Everon"
 m_sAuthor "29th Engineering Corps"
 m_sDescription "29th Drill on Everon"
 m_sDetails "29th Drill Game Mode (GameMaster Base)"
 m_sGameMode "29th Drills"
 m_iPlayerCount 128
 m_iStartingHours 6
 m_bRandomStartingDaytime 1
 m_fNightTimeAcceleration 3
 m_bRandomStartingWeather 1
 m_iMapMarkerLimitPerPlayer 25
 m_bIsArmavisionAllowedInMP 1
}